//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOperationViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class devfwversion_record_
    {
        public string ID { get; set; }
        public string TERM_ID { get; set; }
        public string CRM_VERSION { get; set; }
        public string PIN_VERSION { get; set; }
        public string IDC_VERSION { get; set; }
        public string PTR_VERSION { get; set; }
        public string BCR_VERSION { get; set; }
        public string SIU_VERSION { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
