//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOperationViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_info_
    {
        public string DEVICE_ID { get; set; }
        public string TERM_ID { get; set; }
        public string DEPT_ID { get; set; }
        public string TYPE_ID { get; set; }
        public string BRAND_ID { get; set; }
        public string MODEL_ID { get; set; }
        public string TERM_SEQ { get; set; }
        public string COUNTER_CODE { get; set; }
        public string TERM_IP { get; set; }
        public string STATUS { get; set; }
        public string TERM_NAME { get; set; }
        public string TERM_ADDR { get; set; }
        public string TERM_LOCATION { get; set; }
        public Nullable<double> TERM_ZONE { get; set; }
        public string CONTROL_BY { get; set; }
        public string REPLENISH_BY { get; set; }
        public string POST { get; set; }
        public Nullable<System.DateTime> INSTALL_DATE { get; set; }
        public Nullable<System.DateTime> ACTIVE_DATE { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string INSTALL_TYPE { get; set; }
        public string LAYOUT_TYPE { get; set; }
        public string MAN_ID { get; set; }
        public string SERVICEMAN_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<System.DateTime> SERVICE_BEGINDATE { get; set; }
        public string SERVICE_ENDDATE { get; set; }
        public string SERVICE_YEARS { get; set; }
        public string IS_CCTV { get; set; }
        public Nullable<double> IS_UPS { get; set; }
        public string IS_INTERNATIONAL { get; set; }
        public string BUSINESS_BEGINTIME { get; set; }
        public Nullable<System.DateTime> BUSINESS_ENDTIME { get; set; }
        public string IS_VIP { get; set; }
        public string AREA_ID { get; set; }
        public Nullable<double> AREA_ADDR { get; set; }
        public Nullable<double> FUNCTION_TYPE { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string PROVINCE { get; set; }
        public string LOT_TYPE { get; set; }
        public Nullable<double> AUDITING { get; set; }
        public string CURRENT_IP { get; set; }
        public string VERSION_ATMC { get; set; }
        public string VERSION_SP { get; set; }
        public string VERSION_AGENT { get; set; }
        public string VERSION_MB { get; set; }
        public Nullable<double> FLAG_XFS { get; set; }
        public Nullable<double> FLAG_EJ { get; set; }
        public Nullable<double> FLAG_FSN { get; set; }
        public string EJ_FILES { get; set; }
        public string FSN_PATH { get; set; }
        public string TASK_PARA { get; set; }
        public string VERSION_AD { get; set; }
        public string MODIFY_USERID { get; set; }
        public string MODIFY_DATE { get; set; }
        public string ADD_USERID { get; set; }
        public string ADD_DATE { get; set; }
        public string ASSET_NO { get; set; }
        public string CASH_BOX_NUM { get; set; }
        public string SERVICE_SMS_TYPE { get; set; }
        public string EJ_OPEN_DATE { get; set; }
        public Nullable<System.DateTime> ATMC_UPDATE_TIME { get; set; }
        public Nullable<System.DateTime> SP_UPDATE_TIME { get; set; }
        public Nullable<System.DateTime> AGENT_UPDATE_TIME { get; set; }
        public string VERSION_NV { get; set; }
        public Nullable<System.DateTime> NV_UPDATE_TIME { get; set; }
        public string VERSION_MAIN { get; set; }
        public Nullable<System.DateTime> MAIN_UPDATE_TIME { get; set; }
    }
}
