//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOperationViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_info_system_
    {
        public string SYSTEM_ID { get; set; }
        public string TERM_ID { get; set; }
        public string SYSTEM_NAME { get; set; }
        public Nullable<double> SYSTEM_RAM { get; set; }
        public string SYSTEM_RAM_RATE { get; set; }
        public string SYSTEM_CPU { get; set; }
        public string SYSTEM_CPU_RATE { get; set; }
        public string DISK_USAGE { get; set; }
        public string ADDR_IP { get; set; }
        public string ADDR_MASK { get; set; }
        public string ADDR_GATEWAY { get; set; }
        public string ADDR_DNS { get; set; }
        public string ADDR_DNS_BAK { get; set; }
        public string ADDR_MAC { get; set; }
        public Nullable<System.DateTime> REFLESH_DATE { get; set; }
        public string MEMO { get; set; }
        public Nullable<double> SYSTEM_VOLUME { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
